# Generated by Django 5.2.4 on 2025-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentresponsible',
            name='relation',
            field=models.CharField(choices=[('father', 'Pai'), ('mother', 'Mãe'), ('stepfather', 'Padrasto'), ('stepmother', 'Madrasta'), ('grandparent', 'Avô/Avó'), ('legal_guardian', 'Tutor Legal'), ('other', 'Outro')], max_length=20),
        ),
    ]
