# Generated by Django 5.2.4 on 2025-07-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentresponsible_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
