# Generated by Django 5.2 on 2025-07-11 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_cpf_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='addrees',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
