# Generated by Django 5.2.4 on 2025-07-07 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, unique=True)),
                ('is_current', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(default=2025, on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(default=2025, on_delete=django.db.models.deletion.CASCADE, to='academic.academicyear'),
            preserve_default=False,
        ),
    ]
