# Generated by Django 5.2.4 on 2025-07-07 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_academicyear_classroom_academic_year_and_more'),
        ('accounts', '0003_alter_responsibleprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.classroom'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.studentprofile'),
        ),
    ]
